// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Models.DistanceObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<int?>("SitSmartDeviceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SitSmartDeviceId");

                    b.ToTable("DistanceObjects");
                });

            modelBuilder.Entity("API.Models.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SitSmartDeviceId")
                        .HasColumnType("integer");

                    b.Property<float>("XValue")
                        .HasColumnType("real");

                    b.Property<float>("YValue")
                        .HasColumnType("real");

                    b.Property<float>("ZValue")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("SitSmartDeviceId");

                    b.ToTable("MovementObjects");
                });

            modelBuilder.Entity("API.Models.SitSmartDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SitSmartDevice");
                });

            modelBuilder.Entity("API.Models.TempHumidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Humidity")
                        .HasColumnType("integer");

                    b.Property<int?>("SitSmartDeviceId")
                        .HasColumnType("integer");

                    b.Property<int>("Temp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SitSmartDeviceId");

                    b.ToTable("TempHumidityObjects");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Models.DistanceObject", b =>
                {
                    b.HasOne("API.Models.SitSmartDevice", null)
                        .WithMany("DistanceObjects")
                        .HasForeignKey("SitSmartDeviceId");
                });

            modelBuilder.Entity("API.Models.Movement", b =>
                {
                    b.HasOne("API.Models.SitSmartDevice", null)
                        .WithMany("Movements")
                        .HasForeignKey("SitSmartDeviceId");
                });

            modelBuilder.Entity("API.Models.TempHumidity", b =>
                {
                    b.HasOne("API.Models.SitSmartDevice", null)
                        .WithMany("TempHumiditys")
                        .HasForeignKey("SitSmartDeviceId");
                });

            modelBuilder.Entity("API.Models.SitSmartDevice", b =>
                {
                    b.Navigation("DistanceObjects");

                    b.Navigation("Movements");

                    b.Navigation("TempHumiditys");
                });
#pragma warning restore 612, 618
        }
    }
}
